name: ucs

on:
  schedule:
    - cron: '*/5 * * * *'  # 5分ごとに実行
  workflow_dispatch:

jobs:
  update-clock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch Clock SVG from Vercel
        run: |
          curl -s https://clock-widget.vercel.app/api?date=true -o assets/clock.svg

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/clock.svg
          git commit -m "Update clock SVG" || echo "No changes"
          git push